language: groovy


script: ./gradlew clean check cobertura groovydoc Jar


#filter branches which should be automatically built
branches:
  only:
    - master
    - nonmatrix


#collect build artifacts
jenkins:
  collect:
    artifacts: build/libs/*.jar
    junit: build/test-results/**/*.xml
